In [12]:
# ndnumerate
import numpy as np
arr = np.array([10,20,30,40,50,60,70])
print(arr)
for i in np.ndenumerate(arr):
    print(i)
arr = np.array([[11,22,33],[44,55,66]])
print(arr)
for x in np.ndenumerate(arr):
    print(x)
ar = np.array([[[11,12,13,14,15,16,17,18]]])
print(ar)
for i in np.ndenumerate(ar):
    print(i)
ar[0][0][1]    
ar[0][0][0]

[10 20 30 40 50 60 70]
((0,), 10)
((1,), 20)
((2,), 30)
((3,), 40)
((4,), 50)
((5,), 60)
((6,), 70)
[[11 22 33]
 [44 55 66]]
((0, 0), 11)
((0, 1), 22)
((0, 2), 33)
((1, 0), 44)
((1, 1), 55)
((1, 2), 66)
[[[11 12 13 14 15 16 17 18]]]
((0, 0, 0), 11)
((0, 0, 1), 12)
((0, 0, 2), 13)
((0, 0, 3), 14)
((0, 0, 4), 15)
((0, 0, 5), 16)
((0, 0, 6), 17)
((0, 0, 7), 18)


11

In [18]:
# joining array
arr = np.array([1,2,3])
arr1 = np.array([4,5,6])
arr2 = np.concatenate((arr,arr1))
print(arr2)
arr = np.array([[10,20,30]])
arr1 = np.array([[40,50,60]])
arr3 = np.concatenate((arr,arr1))
print(arr3)
arr = np.array([[[11,22,33]]])
arr1 = np.array([[[44,55,66]]])
arr2 = np.concatenate((arr,arr1))
print(arr2)
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.concatenate((arr1,arr2),axis=0)
print(arr3)
arr1 = np.array([[11,22,33,44]])
arr2 = np.array([[55,66,77,88]])
arr3 = np.concatenate((arr1,arr2),axis=1)
print(arr3)
arr1 = np.array([[[10,20,30,40]]])
arr2 = np.array([[[50,60,70,80]]])
arr3 = np.concatenate((arr1,arr2),axis=2)
print(arr3)

[1 2 3 4 5 6]
[[10 20 30]
 [40 50 60]]
[[[11 22 33]]

 [[44 55 66]]]
[1 2 3 4 5 6]
[[11 22 33 44 55 66 77 88]]
[[[10 20 30 40 50 60 70 80]]]


In [22]:
# using stack function
arr = np.array([1,2,3,4])
arr1 = np.array([5,6,7,8])
arr2 = np.stack((arr,arr1))
print(arr2)
arr1 = np.array([[10,20,30]])
arr2 = np.array([[40,50,60]])
arr3 = np.array([[70,80,90]])
arr4 = np.stack((arr1,arr2,arr3))
print(arr4)
arr1 = np.array([[[11,12,13]]])
arr2 = np.array([[[14,15,16]]])
arr3 = np.array((arr1,arr2))
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]
[[[10 20 30]]

 [[40 50 60]]

 [[70 80 90]]]
[[[[11 12 13]]]


 [[[14 15 16]]]]


In [32]:
# stack usin axis 
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.stack((arr1,arr2),axis=1)
print(arr3)
arr3 = np.stack((arr1,arr2),axis=0)
print(arr3)
arr = np.array([[11,12,13]])
arr1 = np.array([[14,15,16]])
arr2 = np.stack((arr,arr1),axis=1)
print(arr2)
arr2 = np.stack((arr,arr1),axis=0)
print(arr2)
arr = np.array([[[11,22,33]]])
arr1 = np.array([[[44,55,66]]])
arr2 = np.stack((arr,arr1),axis=2)
print(arr2)
arr2 = np.stack((arr,arr1),axis=1)
print(arr2)
arr2 = np.stack((arr,arr1),axis=0)
print(arr2)

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
[[[11 12 13]
  [14 15 16]]]
[[[11 12 13]]

 [[14 15 16]]]
[[[[11 22 33]
   [44 55 66]]]]
[[[[11 22 33]]

  [[44 55 66]]]]
[[[[11 22 33]]]


 [[[44 55 66]]]]


In [35]:
# hstack
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.hstack((a,b))
print(c)
a = np.array([[11,22,33]])
b = np.array([[44,55,66]])
c = np.hstack((a,b))
print(c)
a = np.array([[[10,20,30]]])
b = np.array([[[40,50,60]]])
c = np.hstack((a,b))
print(c)

[1 2 3 4 5 6]
[[11 22 33 44 55 66]]
[[[10 20 30]
  [40 50 60]]]


In [38]:
# vstack
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack((a,b))
print(c)
a = np.array([[11,22,33]])
b = np.array([[44,55,66]])
c = np.vstack((a,b))
print(c)
a = np.array([[[10,20,30]]])
b = np.array([[[40,50,60]]])
c = np.vstack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]
[[11 22 33]
 [44 55 66]]
[[[10 20 30]]

 [[40 50 60]]]


In [41]:
# dstack
ar = np.array([1,2,3])
ar1 = np.array([4,5,6])
ar2 = np.dstack((ar,ar1))
print(ar2)
a = np.array([[10,20,30]])
b = np.array([[40,50,60]])
c = np.dstack((a,b))
print(c)
a = np.array([[[11,12,13]]])
b = np.array([[[14,15,16]]])
c = np.dstack((a,b))
print(c)

[[[1 4]
  [2 5]
  [3 6]]]
[[[10 40]
  [20 50]
  [30 60]]]
[[[11 12 13 14 15 16]]]


In [53]:
# array spliiting
arr = np.array([1,2,3,4,5,6])
print(arr)
a = np.split(arr,3)
print(a)
arr = np.array([[10,20,30],[40,50,60]])
print(arr)
a = np.split(arr,2)
print(a)
arr = np.array([[[11,22,33,44],[55,66,77,88]]])
print(arr)
a = np.split(arr,1)
print(a)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[[10 20 30]
 [40 50 60]]
[array([[10, 20, 30]]), array([[40, 50, 60]])]
[[[11 22 33 44]
  [55 66 77 88]]]
[array([[[11, 22, 33, 44],
        [55, 66, 77, 88]]])]


In [57]:
# split usin axis
a = np.array([10,20,30,40,50,60,70,80])
print(a)
b = np.split(a,2,axis=0)
print(b)
a = np.array([[11,22,33,44],[55,66,77,88]])
print(a)
b = np.split(a,2,axis=1)
print(b)
a = np.array([[[11,12,13],[14,15,16]]])
print(a)
b = np.split(a,3,axis=2)
print(b)
b = np.split(a,2,axis=1)
print(b)

[10 20 30 40 50 60 70 80]
[array([10, 20, 30, 40]), array([50, 60, 70, 80])]
[[11 22 33 44]
 [55 66 77 88]]
[array([[11, 22],
       [55, 66]]), array([[33, 44],
       [77, 88]])]
[[[11 12 13]
  [14 15 16]]]
[array([[[11],
        [14]]]), array([[[12],
        [15]]]), array([[[13],
        [16]]])]
[array([[[11, 12, 13]]]), array([[[14, 15, 16]]])]


In [63]:
# array split method
a = np.array([1,2,3,4,5,6,7,8])
print(a)
b = np.array_split(a,2)
print(b)
a = np.array([[10,20,30],[40,50,60]])
print(a)
b = np.array_split(a,2)
print(b)
a = np.array([[[11,12,13,14],[15,16,17,18]]])
print(a)
b = np.array_split(a,2)
print(b)
print(b[0])
print(b[1])
b = np.array_split(a,2,axis=0)
print(b)


[1 2 3 4 5 6 7 8]
[array([1, 2, 3, 4]), array([5, 6, 7, 8])]
[[10 20 30]
 [40 50 60]]
[array([[10, 20, 30]]), array([[40, 50, 60]])]
[[[11 12 13 14]
  [15 16 17 18]]]
[array([[[11, 12, 13, 14],
        [15, 16, 17, 18]]]), array([], shape=(0, 2, 4), dtype=int32)]
[[[11 12 13 14]
  [15 16 17 18]]]
[]
[array([[[11, 12, 13, 14],
        [15, 16, 17, 18]]]), array([], shape=(0, 2, 4), dtype=int32)]


In [69]:
# array splitting using axis
a = np.array([1,2,3,4,5,6])
print(a)
b = np.array_split(a,2,axis=0)
print(b)
c = np.array_split(a,2,axis=0)
print(c)
a = np.array([[10,20,30],[40,50,60]])
print(a)
b = np.array_split(a,2,axis=1)
print(b)
a = np.array([[[11,12,13],[14,15,16]]])
print(a)
b = np.array_split(a,2,axis=2)
print(b)

[1 2 3 4 5 6]
[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2, 3]), array([4, 5, 6])]
[[10 20 30]
 [40 50 60]]
[array([[10, 20],
       [40, 50]]), array([[30],
       [60]])]
[[[11 12 13]
  [14 15 16]]]
[array([[[11, 12],
        [14, 15]]]), array([[[13],
        [16]]])]


In [76]:
# array split,hsplit,vsplit,dsplit
a = np.array([1,2,3,4])
b = np.hsplit(a,2)
print(b)
a = np.array([[10,20,30],[40,50,60]])
b = np.hsplit(a,1)
print(b)
a = np.array([[[11,12,13],[14,15,16]]])
print(a)
b = np.hsplit(a,1)
print(b)

[array([1, 2]), array([3, 4])]
[array([[10, 20, 30],
       [40, 50, 60]])]
[[[11 12 13]
  [14 15 16]]]
[array([[[11, 12, 13],
        [14, 15, 16]]])]


In [84]:
# vsplit
a = np.array([[10,20,30],[40,50,60]])
b = np.vsplit(a,1)
print(b)
b =np.vsplit(a,2)
print(b)
a = np.array([[[11,12,13],[14,15,16]]])
b = np.vsplit(a,1)
print(b)

[array([[10, 20, 30],
       [40, 50, 60]])]
[array([[10, 20, 30]]), array([[40, 50, 60]])]
[array([[[11, 12, 13],
        [14, 15, 16]]])]


In [88]:
# dsplit
a = np.array([[[10,20,30],[40,50,60]]])
b = np.dsplit(a,1)
print(b)
a = np.array([[[11,12,13],[14,15,16]]])
print(a)
b = np.dsplit(a,1)
print(b)

[array([[[10, 20, 30],
        [40, 50, 60]]])]
[[[11 12 13]
  [14 15 16]]]
[array([[[11, 12, 13],
        [14, 15, 16]]])]


In [96]:
# searching array
a = np.array([1,2,3,4,5,6])
print(a)
b = np.where(a==3)
print(b)
c = np.where(a==4)
print(c)
d = np.where(a==6)
print(d)
a = np.array([[10,20,30],[40,50,60]])
print(a)
b = np.where(a==2)
print(b)
c = np.where(a==3)
print(c)
d = np.where(a==0)
print(d)


[1 2 3 4 5 6]
(array([2], dtype=int64),)
(array([3], dtype=int64),)
(array([5], dtype=int64),)
[[10 20 30]
 [40 50 60]]
(array([], dtype=int64), array([], dtype=int64))
(array([], dtype=int64), array([], dtype=int64))
(array([], dtype=int64), array([], dtype=int64))


In [111]:
# searching array
a = np.array([10,20,30])
print(a)
b = np.where(a==1)
print(b)
print(a-1)
print(a+1)
a = np.array([[11,12,13],[14,15,16]])
print(a)
b = np.where(a==2)
print(b)
print(a+1)
print(a-1)
print(a*1)
a = np.array([[[11,22,33],[44,55,66]]])
print(a)
b = np.where(a==2)
print(b)
print(a+1)
print(a-1)
print(a*1)
print(a/1)

[10 20 30]
(array([], dtype=int64),)
[ 9 19 29]
[11 21 31]
[[11 12 13]
 [14 15 16]]
(array([], dtype=int64), array([], dtype=int64))
[[12 13 14]
 [15 16 17]]
[[10 11 12]
 [13 14 15]]
[[11 12 13]
 [14 15 16]]
[[[11 22 33]
  [44 55 66]]]
(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))
[[[12 23 34]
  [45 56 67]]]
[[[10 21 32]
  [43 54 65]]]
[[[11 22 33]
  [44 55 66]]]
[[[11. 22. 33.]
  [44. 55. 66.]]]


In [114]:
# even and odd
arr = np.array([1,2,3,4,5,6])
print(arr)
a = np.where(arr%2==1)
print(a)
a = np.array([[10,20,30],[40,50,60]])
print(a)
b = np.where(a%2==0)
print(b)
a = np.array([[[11,12,13,14,15,16]]])
print(a)
b = np.where(a%2==1)
print(b)

[1 2 3 4 5 6]
(array([0, 2, 4], dtype=int64),)
[[10 20 30]
 [40 50 60]]
(array([0, 0, 0, 1, 1, 1], dtype=int64), array([0, 1, 2, 0, 1, 2], dtype=int64))
[[[11 12 13 14 15 16]]]
(array([0, 0, 0], dtype=int64), array([0, 0, 0], dtype=int64), array([0, 2, 4], dtype=int64))


In [120]:
# searchsorted
a = np.array([1,2,3,4,5,6,7])
print(a)
b = np.searchsorted(a,5)
print(b)
a = np.array([10,20,30,40,50])
print(a)
b = np.searchsorted(a,30)
print(b)

[1 2 3 4 5 6 7]
4
[10 20 30 40 50]
2


In [124]:
# side
a = np.array([11,12,13,14,15,16])
print(a)
b = np.searchsorted(a,12,side='right')
print(b)
b = np.searchsorted(a,13,side='right')
print(b)
b = np.searchsorted(a,12,side='left')
print(b)

[11 12 13 14 15 16]
2
3
1


In [125]:
# multiple values
a = np.array([1,2,3,4,5])
print(a)
b = np.searchsorted(a,[11,13,15])
print(b)

[1 2 3 4 5]
[5 5 5]


In [126]:
a = np.array([1,3,5,7,9])
print(a)
b = np.searchsorted(a,[2,4,6,8])
print(b)

[1 3 5 7 9]
[1 2 3 4]


In [129]:
# sorting array
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
b = np.sort(a)
print(b)
a = np.array([[13,14,17,18]])
print(a)
b = np.sort(a)
print(b)
a = np.array([[[400,300,200,100]]])
print(a)
b = np.sort(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[[13 14 17 18]]
[[13 14 17 18]]
[[[400 300 200 100]]]
[[[100 200 300 400]]]


In [132]:
# alphabetical array
a = np.array(['cc','dd','aa','ff','gg'])
print(a)
b = np.sort(a)
print(b)
a = np.array([True,False])
print(a)
b = np.sort(a)
print(b)

['cc' 'dd' 'aa' 'ff' 'gg']
['aa' 'cc' 'dd' 'ff' 'gg']
[ True False]
[False  True]


In [138]:
# sorting array using axis
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = np.sort(a,axis=1)
print(b)
a = np.array([[[10,30,20],[50,60,40]]])
print(a)
b = np.sort(a,axis=2)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[[10 30 20]
  [50 60 40]]]
[[[10 20 30]
  [40 50 60]]]


In [145]:
# filter array
a = np.array([10,20,30,40])
b =[True,True,False,True]
c = a[b]
print(c)
a = np.array([[10,20,30],[40,50,60]])
b =[[True,False,True],[True,False,True]]
c= a[b]
print(c)
a = np.array([[[1,2,3],[4,5,6]]])
b = [[[True,False,True],[True,False,True]]]
c = a[b]
print(c)

[10 20 40]
[10 30 40 60]
[1 3 4 6]


In [150]:
a = np.array([1,2,3,6,5,7,9,8])
print(a)
index=[]
for i in a:
    print(i)
    if i<40:
        index.append(True)
    else:
        index.append(False)
print(index)
ar = a[index]
print(ar)

[1 2 3 6 5 7 9 8]
1
2
3
6
5
7
9
8
[True, True, True, True, True, True, True, True]
[1 2 3 6 5 7 9 8]


In [155]:
a = np.array([10,20,30,40])
print(a)
index=[]
for i in a:
    print(i)
    if i%2==0:
        index.append(True)
    else:
        index.append(False)
print(index)
ar = a[index]
print(ar)

[10 20 30 40]
10
20
30
40
[True, True, True, True]
[10 20 30 40]


In [158]:
# other numpy function
a = np.arange(20)
print(a)
print(type(a))
b = a.reshape(10,2)
print(b)
c = a.reshape(10,2,1)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
[[[ 0]
  [ 1]]

 [[ 2]
  [ 3]]

 [[ 4]
  [ 5]]

 [[ 6]
  [ 7]]

 [[ 8]
  [ 9]]

 [[10]
  [11]]

 [[12]
  [13]]

 [[14]
  [15]]

 [[16]
  [17]]

 [[18]
  [19]]]


In [160]:
a = np.arange(30)
print(a)
print(type(a))
print(a[0])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
<class 'numpy.ndarray'>
0


In [176]:
a = np.arange(40)
print(a)
print(type(a))
print(a.min())
print(a.max())
print(a.argmax())
print(a.argmin())
print(a.argsort())
print(a.sum())
print(a.mean())
print(a.nonzero())
b = a.reshape(10,4)
print(b)
print(b.diagonal())
a = np.linspace(8,5,1)
print(a)
b = np.linspace(20,4,1)
print(b)
c = np.linspace(50,1,10)
print(c)
print(a.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
<class 'numpy.ndarray'>
0
39
39
0
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
780
19.5
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39], dtype=int64),)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
[ 0  5 10 15]
[8.]
[20.]
[50.         44.55555556 39.11111111 33.66666667 28.22222222 22.77777778
 17.33333333 11.88888889  6.44444444  1.        ]
[8.]


In [182]:
a = np.arange(25)
print(a)
print(type(a))
ar = np.random.randn(5,5)
print(ar)
ar = np.eye(5,5)
print(ar)
ar = np.ones((5,5))
print(ar)
arr = np.diag([1,2,3])
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
<class 'numpy.ndarray'>
[[ 1.07948268 -0.53594859  0.24326814  1.81386401 -0.79267794]
 [ 2.09604867  0.81992569 -0.33206796 -0.30319989 -0.91135068]
 [ 0.47715595 -1.24548658 -0.35996873 -0.49867136 -0.08987656]
 [ 1.86498873 -0.64463011 -0.30004743 -1.01467821 -0.53251762]
 [-0.07724586 -1.40654028  1.77728325 -1.77678195 -0.66374821]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [183]:
arr = np.array([1,2,3,4,5,6])
print(arr)
for x in np.ndenumerate(arr):
    print(x)

[1 2 3 4 5 6]
((0,), 1)
((1,), 2)
((2,), 3)
((3,), 4)
((4,), 5)
((5,), 6)


In [184]:
arr = np.array([1,2,3])
arr1 = np.array([4,5,6])
arr2 = np.concatenate((arr,arr1))
print(arr2)

[1 2 3 4 5 6]


In [185]:
arr = np.array([[11,12,13]])
arr1 = np.array([[14,15,16]])
arr2 = np.concatenate((arr,arr1),axis=1)
print(arr2)

[[11 12 13 14 15 16]]


In [189]:
ar = np.array([10,20,30,40,50])
print(ar)
a = np.stack(ar)
print(a)
ar = np.array([[10,20,30],[40,50,60]])
print(ar)
a = np.stack(ar)
print(a)
a[0][1]
a[0][2]

[10 20 30 40 50]
[10 20 30 40 50]
[[10 20 30]
 [40 50 60]]
[[10 20 30]
 [40 50 60]]


30

In [191]:
a = np.array([1,2,3,4,5])
print(a)
b = np.hstack(a)
print(b)
a = np.array([[10,20,30],[40,50,60]])
print(a)
b = np.hstack(a)
print(b)

[1 2 3 4 5]
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]
[10 20 30 40 50 60]


In [192]:
a = np.array([[[1,2,3],[4,5,6]]])
print(a)
b = np.vstack(a)
print(b)

[[[1 2 3]
  [4 5 6]]]
[[1 2 3]
 [4 5 6]]


In [195]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.dstack((a,b))
print(c)

[[[1 4]
  [2 5]
  [3 6]]]


In [198]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)
b = np.split(arr,2)
print(b)
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
a = np.array_split(arr,2)
print(a)

[1 2 3 4 5 6 7 8]
[array([1, 2, 3, 4]), array([5, 6, 7, 8])]
[[1 2 3]
 [4 5 6]]
[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [200]:
arr = np.array([[1,2,3,4,5,6]])
print(arr)
a = np.split(arr,2,axis=1)
print(a)
arr = np.array([[[1,2,3],[4,5,6]]])
a = np.array_split(arr,2,axis=2)
print(a)

[[1 2 3 4 5 6]]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
[array([[[1, 2],
        [4, 5]]]), array([[[3],
        [6]]])]


In [202]:
a = np.array([1,2,3,4,5,6])
a = np.where(a==2)
print(a)
ar = np.array([[1,2,3],[4,5,6]])
print(ar)
b = np.where(ar==4)
print(b)

(array([1], dtype=int64),)
[[1 2 3]
 [4 5 6]]
(array([1], dtype=int64), array([0], dtype=int64))


In [204]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a+1)
print(a-1)

[[1 2 3]
 [4 5 6]]
[[2 3 4]
 [5 6 7]]
[[0 1 2]
 [3 4 5]]


In [205]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = np.where(a%2==0)
print(b)

[[1 2 3]
 [4 5 6]]
(array([0, 1, 1], dtype=int64), array([1, 0, 2], dtype=int64))


In [206]:
a = np.array([1,2,4,5,6])
print(a)
b = np.searchsorted(a,3)
print(b)

[1 2 4 5 6]
2


In [207]:
a = np.array([1,2,3,4,5,6,7,8])
print(a)
b = np.searchsorted(a,4,side='right')
print(b)


[1 2 3 4 5 6 7 8]
4


In [208]:
a = np.array([1,3,5,7,9])
print(a)
b = np.searchsorted(a,[2,4,6])
print(b)

[1 3 5 7 9]
[1 2 3]


In [209]:
a = np.array([3,5,7,6,4])
print(a)
b = np.sort(a)
print(b)

[3 5 7 6 4]
[3 4 5 6 7]


In [212]:
a = np.array(['bb','ff','rr','tt','aa'])
print(a)
b = np.sort(a)
print(b)
a = np.array([True,False])
print(a)
b = np.sort(a)
print(b)

['bb' 'ff' 'rr' 'tt' 'aa']
['aa' 'bb' 'ff' 'rr' 'tt']
[ True False]
[False  True]


In [214]:
a = np.array([[1,2,3],[6,5,4]])
print(a)
b = np.sort(a,axis=0)
print(b)
c = np.sort(a,axis=1)
print(c)

[[1 2 3]
 [6 5 4]]
[[1 2 3]
 [6 5 4]]
[[1 2 3]
 [4 5 6]]


In [215]:
a = np.array([1,3,2,4])
b = [True,False,True,False]
c = a[b]
print(c)


[1 2]


In [220]:
a = np.array([1,2,3,4,5,6,7,8])
print(a)
index=[]
for i in a:
    print(i)
    if i%2==1:
        index.append(True)
    else:
        index.append(False)
print(a)
ar = a[index]
print(ar)

[1 2 3 4 5 6 7 8]
1
2
3
4
5
6
7
8
[1 2 3 4 5 6 7 8]
[1 3 5 7]


In [224]:
a = np.arange(20)
print(a)
print(type(a))
b = a.reshape(4,5)
print(b)
c = a.reshape(4,5,1)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]
  [14]]

 [[15]
  [16]
  [17]
  [18]
  [19]]]


In [228]:
a = np.arange(30)
print(a)
print(a.min())
print(a.max())
print(a.argmax())
print(a.argmin())
print(a.argsort())
print(a.sum())
print(a.mean())
print(a.nonzero())
b = a.reshape(5,6)
print(b)
print(b.diagonal())
print(b.ravel())


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
0
29
29
0
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
435
14.5
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int64),)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[ 0  7 14 21 28]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [232]:
a = np.arange(20)
print(a)
print(type(a))
b = np.linspace(21,2,1)
print(b)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
[21.]


In [233]:
a = np.arange(30)
print(a)
print(type(a))
b = np.random.randn(5,6)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
<class 'numpy.ndarray'>
[[-0.04207242 -1.15445325 -0.16167752  1.17030544 -1.23455135 -2.27242452]
 [-0.58381378  0.25616439  0.59255086 -0.5419785   0.33777863  0.1396802 ]
 [ 0.81890061  0.93264992 -0.03862485  0.36448242  0.59027886 -1.49817725]
 [-0.33814185 -0.41025999 -1.45803422 -0.0308039   0.57424696  0.73703258]
 [ 0.78243903  1.17004706  0.09188262  1.50950825  0.37352453  1.75350092]]


In [235]:
a = np.eye(5,6)
print(a)
b = np.ones((15,2))
print(b)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [242]:
a = np.arange(25)
print(a)
b = np.diag([2,3])
print(b)
a*2
b = a.dot(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[2 0]
 [0 3]]
4900


In [244]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
for x in np.ndenumerate(a):
    print(x)
    

[[1 2 3]
 [4 5 6]]
((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((1, 0), 4)
((1, 1), 5)
((1, 2), 6)


In [246]:
a = np.array([[[1,2,3],[4,5,6]]])
print(a)
for x in np.ndenumerate(a):
    print(x)
a[0]    

[[[1 2 3]
  [4 5 6]]]
((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 0, 2), 3)
((0, 1, 0), 4)
((0, 1, 1), 5)
((0, 1, 2), 6)


array([[1, 2, 3],
       [4, 5, 6]])

In [247]:
# joining array
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [248]:
a = np.array([[10,20,30]])
b = np.array([[40,50,60]])
c = np.concatenate((a,b),axis=1)
print(c)

[[10 20 30 40 50 60]]


In [256]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.stack((a,b))
print(c)
a = np.array([[[10,20,30]]])
b = np.array([[[40,50,60]]])
c = np.stack((a,b))
print(c)
print(c[0][0])

[[1 2 3]
 [4 5 6]]
[[[[10 20 30]]]


 [[[40 50 60]]]]
[[10 20 30]]


In [258]:
a = np.array([[10,20,30]])
b = np.array([[40,50,60]])
c = np.hstack((a,b))
print(c)

[[10 20 30 40 50 60]]


In [259]:
a = np.array([[[1,2,3]]])
b = np.array([[[4,5,6]]])
c = np.vstack((a,b))
print(c)

[[[1 2 3]]

 [[4 5 6]]]


In [260]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
c = np.dstack((a,b))
print(c)

[[[1 4]
  [2 5]
  [3 6]]]


In [263]:
a = np.array([10,20,30,40,50,60])
print(a)
b = np.split(a,2)
print(b)
c = np.split(a,3)
print(c)

[10 20 30 40 50 60]
[array([10, 20, 30]), array([40, 50, 60])]
[array([10, 20]), array([30, 40]), array([50, 60])]


In [268]:
a = np.array([[11,12,13,14,15,16,17,18]])
print(a)
b = np.split(a,1)
print(b)
c = np.split(a,2,axis=1)
print(c)

[[11 12 13 14 15 16 17 18]]
[array([[11, 12, 13, 14, 15, 16, 17, 18]])]
[array([[11, 12, 13, 14]]), array([[15, 16, 17, 18]])]


In [270]:
a = np.array([1,2,3,4,5,6,7,8])
print(a)
b = np.array_split(a,4)
print(b)
c = np.array_split(a,5,axis=0)
print(c)

[1 2 3 4 5 6 7 8]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7]), array([8])]


In [271]:
a = np.array([[10,20,30,40,50,60]])
print(a)
b = np.array_split(a,3,axis=1)
print(b)


[[10 20 30 40 50 60]]
[array([[10, 20]]), array([[30, 40]]), array([[50, 60]])]


In [272]:
a = np.array([[[11,22,33,44,55,66]]])
print(a)
b = np.array_split(a,3,axis=2)
print(b)


[[[11 22 33 44 55 66]]]
[array([[[11, 22]]]), array([[[33, 44]]]), array([[[55, 66]]])]


In [279]:
a = np.array([1,2,3,4,5,6,7,8])
print(a)
b = np.where(a==2)
print(b)
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = np.where(a%2==0)
print(b)
a
print(a-1)
print(a**1)
print(a%2)

[1 2 3 4 5 6 7 8]
(array([1], dtype=int64),)
[[1 2 3]
 [4 5 6]]
(array([0, 1, 1], dtype=int64), array([1, 0, 2], dtype=int64))
[[0 1 2]
 [3 4 5]]
[[1 2 3]
 [4 5 6]]
[[1 0 1]
 [0 1 0]]


In [282]:
a= np.array([1,2,3,4,5,6,7,8])
print(a)
b = np.where(a%2==1)
print(b)


[1 2 3 4 5 6 7 8]
(array([0, 2, 4, 6], dtype=int64),)


In [283]:
a = np.array([1,2,3,4,5,6,7])
print(a)
b = np.searchsorted(a,4)
print(b)

[1 2 3 4 5 6 7]
3


In [284]:
a = np.array([1,2,3,4,5,6,7,8])
print(a)
b = np.searchsorted(a,4,side='left')
print(b)

[1 2 3 4 5 6 7 8]
3


In [285]:
a = np.array([1,3,5,7])
b = np.searchsorted(a,[2,4,6])
print(b)

[1 2 3]


In [286]:
a = np.array([[3,5,4,7,6,8,2]])
b = np.sort(a)
print(b)

[[2 3 4 5 6 7 8]]


In [287]:
a = np.array(['gg','aa','uu','cc'])
print(a)
b = np.sort(a)
print(b)

['gg' 'aa' 'uu' 'cc']
['aa' 'cc' 'gg' 'uu']


In [288]:
a = np.array([[[1,3,2],[6,5,4]]])
b = np.sort(a,axis=2)
print(b)

[[[1 2 3]
  [4 5 6]]]


In [290]:
a = np.array([[1,2,3]])
b = [[True,False,True]]
c = a[b]
print(c)

[1 3]


In [291]:
a= np.array([1,2,3,4,5])
print(a)
index=[]
for i in a:
    print(i)
    if i<5:
        index.append(True)
    else:
        index.append(False)
print(index)
ar = a[index]
print(ar)
    

[1 2 3 4 5]
1
2
3
4
5
[True, True, True, True, False]
[1 2 3 4]


In [295]:
a = np.arange(30)
print(a)
print(type(a))
print(a.min())
print(a.max())
print(a.argmax())
print(a.argmin())
print(a.argsort())
print(a.sum())
print(a.mean())
print(a.nonzero())
b = a.reshape(5,6)
print(b)
print(b.diagonal())
print(b.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
<class 'numpy.ndarray'>
0
29
29
0
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
435
14.5
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int64),)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[ 0  7 14 21 28]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [303]:
a = np.arange(25)
print(a)
b = np.linspace(5,5,2)
print(b)
b = np.random.randn(5,5)
print(b)
c = np.eye(5,5)
print(c)
d = np.ones((5,5))
print(d)
e = np.diag([2,3,4])
print(e)
z = e.dot(e)
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[5. 5.]
[[-1.45420633 -0.05001429 -0.49024848  0.36010944 -0.94593767]
 [-1.33745413  1.0791032  -0.30176649 -0.96619692 -1.36240505]
 [ 0.50147852 -1.29305138  0.27055342 -0.12138099  0.29889121]
 [-0.45588661  1.51579213 -2.04016664 -0.57470103  1.60477349]
 [-0.78976636  2.37958183  0.54253977 -1.52559254 -0.21970047]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[2 0 0]
 [0 3 0]
 [0 0 4]]
[[ 4  0  0]
 [ 0  9  0]
 [ 0  0 16]]
